quarkus.operator-sdk.controllers.sconeosvscannerreconciler.namespaces=${WATCH_NAMESPACE:}

# Helm chart metadata
quarkus.helm.name=scone-osv-scanner-k8-operator
quarkus.helm.description=Kubernetes operator for SCONE OSV Scanner
