apiVersion: youssefhenna.com/v1
kind: SconeOsvScanner
metadata:
  name: osv-scanner-sample
spec:
  registryUrl: registry.scontain.com
  registryRepository: scone.cloud/sos-images
  registryCredentials:
    secretRef:
      name: scontain-git-secret
  casAddress: cas.default
  dbManagerSpec:
    imageName: dbmanager
    imageVersion: 5.10.0-rc.5
    replicas: 1
    memory: 12G
    sconeConfigId: scone-osv-scan/dbmanager_service
  frontAppSpec:
    imageName: osvscan
    imageVersion: 5.10.0-rc.5
    replicas: 1
    memory: 5G
    sconeConfigId: scone-osv-scan/osvscan_service
  databaseSpec:
    registryUrl: registry.scontain.com
    registryRepository: sconecuratedimages
    registryCredentials:
      secretRef:
        name: scontain-git-secret
    maxscaleSpec:
      imageName: apps
      imageVersion: maxscale-2.5-alpine-scone5
      replicas: 1
      memory: 2G
      sconeConfigId: scone-osv-scan/maxscale
    mariadbPrimarySpec:
      imageName: apps
      imageVersion: mariadb-alpine-scone5.0
      replicas: 1
      memory: 4G
      sconeConfigId: scone-osv-scan/mariadb_primary
      storageSize: 10Gi
    mariadbReplicaSpec:
      imageName: apps
      imageVersion: mariadb-alpine-scone5.0
      replicas: 1
      memory: 4G
      sconeConfigId: scone-osv-scan/mariadb_replica
      storageSize: 10Gi