package com.youssefhenna.status;

public enum PolicyUpdateState {
    FAILED_INVALID_SPOL,
    FAILED_READ_EXISTING_FORBIDDEN,
    FAILED_UNKNOWN_READ_EXISTING_FAILURE,
    FAILED_UNKNOWN_CAS_ERROR,
    FAILED_SESSION_COMPARISON_FAILURE,
    FAILED_NAMESPACE_NOT_FOUND,
    FAILED_SIGNER_NOT_AUTHORIZED,
    FAILED_PREDECESSOR_CONFLICT,
    FAILED_UNKNOWN_UPLOAD_SESSION_FAILURE,
    SKIPPED_CAS_ALREADY_UPTODATE,
    SUCCESS_UPLOADED,
}
